update scripts

diff --git a/bin/repo-tag b/bin/repo-tag
--- a/bin/repo-tag
+++ b/bin/repo-tag
@@ -10,20 +10,22 @@ die() {
 	exit 1
 }
 
-_f() {
+has() {
 	local ret="1"
 
 	[ "$1" ] || return "$ret"
 	[ "$1" -eq "${FLAGS_FALSE}" ] && return "$ret"
 
-	local ret="0"
+	ret="0"
 	return "$ret"
 }
 
 DEFINE_boolean 'force' false 'Forced update' 'f'
-DEFINE_boolean 'skip' false 'Skip and process manifest only' 's'
-DEFINE_string 'remote' '' 'Specify remote name' 'r'
+DEFINE_boolean 'skip' false 'Skip working tree, process manifest only' 's'
+DEFINE_string 'remote' 'gbc_official' 'Specify remote name' 'r'
 DEFINE_boolean 'debug' false 'Enable debug mode' 'd'
+DEFINE_boolean 'network' false 'Network sync' 'n'
+DEFINE_boolean 'tag' false 'tag for each repository' 't'
 
 FLAGS_HELP=`cat <<EOT
 Usage:
@@ -45,7 +47,7 @@ EOT`
 FLAGS "$@" || exit 1
 eval set -- "${FLAGS_ARGV}"
 
-_f "${FLAGS_help}" && exit 0
+has "${FLAGS_help}" && exit 0
 
 branch="$1"
 [ "$branch" ] || die
@@ -55,9 +57,8 @@ manifest="default.xml"
 [ "$2" ] && manifest="$2"
 
 remote="${FLAGS_remote}"
-_f "${FLAGS_skip}" && skip="1"
-_f "${FLAGS_force}" && force="-f"
-_f "${FLAGS_debug}" && debug="1"
+has "${FLAGS_force}" && force="-f"
+has "${FLAG_network}" || network="-l"
 
 # DEBUG options {{{
 #debug=1
@@ -67,7 +68,6 @@ if [ "$debug" ]; then
 	echo "tag \"$tag\""
 	echo "remote \"$remote\""
 	echo "force \"$force\""
-	echo "skip \"$skip\""
 	echo "debug \"$debug\""
 	echo "help \"$help\""
 
@@ -75,34 +75,28 @@ if [ "$debug" ]; then
 fi
 # }}}
 
-if [ ! "$skip" ]; then
-	[ "$remote" ] || remote="gbc_official"
-
-	echo 1
-	repo forall -c "git clear; git checkout \"`git rev-parse HEAD`\"" > /dev/null 2>&1
-	repo sync -d -l -j4 > /dev/null 2>&1
-
-	echo 2
-	repo init -m "$manifest" > /dev/null 2>&1
-	repo forall -c "git branch -D _tmp; git branch _tmp; git tag -d \"$tag\"; git tag -m \"init $branch tag\" \"$tag\" _tmp ;" > /dev/null 2>&1
-	repo forall -c "git push $force $remote \"$tag\":\"$tag\" ; git push $force $remote _tmp:\"$branch\";"
-
-	echo 3
-	repo forall -c "git clear; git checkout \"`git rev-parse HEAD`\"" > /dev/null 2>&1
-	repo forall -c "git branch -D _tmp; " > /dev/null 2>&1
-
-	repo forall -c "git tag -d \"$tag\"" > /dev/null 2>&1
+# manifest {{{
+if [ -f ~/.andrc ]; then
+	. ~/.andrc
+elif [ -f build/envsetup.sh ]; then
+	. build/envsetup.sh
+else
+	die "envsetup failed"
 fi
 
-# manifest {{{
-. ~/.andrc
-croot
+croot || die "croot failed"
 
 echo 4
-pushd .repo/manifests
-git branch -D _tmp > /dev/null 2>&1
-git checkout -b _tmp > /dev/null 2>&1
+pushd ".repo/manifests"
+git checkout default
+git branch -D _tmp
+git checkout -b _tmp
+
 echo 5
+repo manifest -r -o "${tag}.xml"
+git add "${tag}.xml"
+git commit -am "Import ${tag}.xml"
+
 #sed -i "s#\(^.*<default\s\+\w*\s*remote=\"gbc_official\"\s\+\w*\s*revision=\"\)[^\"]*\(\"\s*\w*\s*/>\)#$branch#" default.xml > /dev/null 2>&1
 if [ "$remote" ]; then
 	sed -i "s#\(^.*<default\s\+remote=\"\)[^\"]*\(\"\s\+revision=\"\)[^\"]*\(\"\s*\w*\s*/>\)#\\1$remote\\2$branch\\3#" default.xml > /dev/null 2>&1
@@ -113,15 +107,17 @@ git commit -a -m "init $branch" > /dev/null 2>&1
 git push origin $force _tmp:"$branch"
 
 echo 6
-if [ "$remote" ]; then
-	sed -i "s#\(^.*<default\s\+remote=\"\)[^\"]*\(\"\s\+revision=\"\)[^\"]*\(\"\s*\w*\s*/>\)#\\1$remote\\2refs/tags/$tag\\3#" default.xml > /dev/null 2>&1
-else
-	sed -i "s#\(^.*<default\s\+remote=\"[^\"]*\"\s\+revision=\"\)[^\"]*\(\"\s*\w*\s*/>\)#\\1refs/tags/$tag\\2#" default.xml > /dev/null 2>&1
+if has "${FLAGS_tag}"; then
+	if [ "$remote" ]; then
+		sed -i "s#\(^.*<default\s\+remote=\"\)[^\"]*\(\"\s\+revision=\"\)[^\"]*\(\"\s*\w*\s*/>\)#\\1$remote\\2refs/tags/$tag\\3#" default.xml > /dev/null 2>&1
+	else
+		sed -i "s#\(^.*<default\s\+remote=\"[^\"]*\"\s\+revision=\"\)[^\"]*\(\"\s*\w*\s*/>\)#\\1refs/tags/$tag\\2#" default.xml > /dev/null 2>&1
+	fi
+	git commit -a -m "init $tag tag" > /dev/null 2>&1
+	git tag -d "$tag" > /dev/null 2>&1
+	git tag -m "init $tag tag" "$tag" > /dev/null 2>&1
+	git push origin $force "$tag":"$tag"
 fi
-git commit -a -m "init $tag tag" > /dev/null 2>&1
-git tag -d "$tag" > /dev/null 2>&1
-git tag -m "init $tag tag" "$tag" > /dev/null 2>&1
-git push origin "$force" "$tag":"$tag"
 
 echo 7
 git reset --hard > /dev/null 2>&1
@@ -130,4 +126,24 @@ git reset --hard origin/default > /dev/null 2>&1
 git branch -D _tmp > /dev/null 2>&1
 popd
 # manifest }}}
+
+if ! has "${FLAGS_skip}"; then
+	echo 1
+	repo sync -d ${network} -j4 > /dev/null 2>&1
+	repo forall -c "git clear; git checkout \$(git rev-parse HEAD)" > /dev/null 2>&1
+
+	echo 2
+	repo init -m "$manifest" > /dev/null 2>&1
+	repo forall -c "git branch -D _tmp; git branch _tmp; " > /dev/null 2>&1
+	if has "${FLAGS_tag}"; then
+		repo forall -c "git tag -d \"$tag\"; git tag -m \"init $branch tag\" \"$tag\" _tmp" > /dev/null 2>&1
+		repo forall -c "git push $force $remote \"$tag\":\"$tag\""
+		repo forall -c "git tag -d \"$tag\"" > /dev/null 2>&1
+	fi
+	repo forall -c "git push $force \"$remote\" _tmp:\"$branch\""
+
+	echo 3
+	repo forall -c "git clear; git checkout \$(git rev-parse HEAD)" > /dev/null 2>&1
+	repo forall -c "git branch -D _tmp; " > /dev/null 2>&1
+fi
 
