update

diff --git a/bin/sandiego-fresh-build b/bin/sandiego-fresh-build
--- a/bin/sandiego-fresh-build
+++ b/bin/sandiego-fresh-build
@@ -21,7 +21,7 @@ function build() {
 
 	repo forall -c "git reset --hard && git clean -df"
 	#repo forall -p -c "git checkout sku1/M76XXTSNCJNLYA60401002_7050_DSDS_dvt2_w1104"
-	repo sync
+	repo sync -d
 
 	. /home/andrew/.andrchoose
 
@@ -39,7 +39,7 @@ function build() {
 	mkctagscope
 	repo forall -c 'mkctagscope'
 
-	make || make clean || make
+	make || ( make clean && make )
 }
 
 function backup() {
@@ -47,36 +47,33 @@ function backup() {
 	return 0
 }
 
-echo "repo-sync $WORKSPACE/mirror"
-repo-sync "$WORKSPACE/mirror" || echo "mirror: repo-sync fail"
+#echo "repo-sync $WORKSPACE/mirror"
+#repo-sync "$WORKSPACE/mirror" || echo "mirror: repo-sync fail"
 
-#echo "repo-sync $WORKSPACE/daily/dsds/base/android"
-#repo-sync "$WORKSPACE/daily/dsds/base/android" || echo "base: repo-sync fail"
-
-echo "build $WORKSPACE/daily/dsds/pure_7050_qrd/android"
-build "$WORKSPACE/daily/dsds/pure_7050_qrd/android"
-backup
-
-#echo "repo-sync $WORKSPACE/daily/dsds/base/android"
-#repo-sync "$WORKSPACE/daily/dsds/base/android" || echo "pure: repo-sync fail"
-
-#echo "build $WORKSPACE/daily/dsds/base/android $GBC_FEATURE_PROVIDER_PATH/project_config/GSmart_DSDS.cfg"
-#build "$WORKSPACE/daily/dsds/base/android" "$GBC_FEATURE_PROVIDER_PATH/project_config/GSmart_DSDS.cfg"
+#echo "build $WORKSPACE/daily/dsds/pure_7050_qrd/android"
+#build "$WORKSPACE/daily/dsds/pure_7050_qrd/android" | tee /tmp/dsds-pure_7050_qrd.log
 #backup
 
-#echo "build $WORKSPACE/daily/dsds/base_7050/android $GBC_FEATURE_PROVIDER_PATH/project_config/GSmart_DSDS.cfg"
-#build "$WORKSPACE/daily/dsds/base_7050/android" "$GBC_FEATURE_PROVIDER_PATH/project_config/GSmart_DSDS.cfg"
+##echo "build $WORKSPACE/daily/dsds/base_7050_qrd/android $GBC_FEATURE_PROVIDER_PATH/project_config/GSmart_DSDS.cfg"
+##build "$WORKSPACE/daily/dsds/base_7050_qrd/android" "$GBC_FEATURE_PROVIDER_PATH/project_config/GSmart_DSDS.cfg" | tee /tmp/dsds-base_7050_qrd.log
+##backup
+
+#echo "build $WORKSPACE/daily/ssss/pure/android"
+#build "$WORKSPACE/daily/ssss/pure/android" | tee /tmp/ssss-pure.log
 #backup
 
-echo "build $WORKSPACE/daily/dsds/base_7050_qrd/android $GBC_FEATURE_PROVIDER_PATH/project_config/GSmart_DSDS.cfg"
-build "$WORKSPACE/daily/dsds/base_7050_qrd/android" "$GBC_FEATURE_PROVIDER_PATH/project_config/GSmart_DSDS.cfg"
+#echo "build $WORKSPACE/daily/ssss/base/android $GBC_FEATURE_PROVIDER_PATH/project_config/GSmart_SSSS.cfg"
+#build "$WORKSPACE/daily/ssss/base/android" "$GBC_FEATURE_PROVIDER_PATH/project_config/GSmart_SSSS.cfg" | tee /tmp/ssss-base.log
+#backup
+
+echo "build $WORKSPACE/daily/dsds/obm/android"
+#build "$WORKSPACE/daily/dsds/obm/android" | tee /tmp/dsds-obm.log
 backup
 
-echo "build $WORKSPACE/daily/ssss/pure/android"
-build "$WORKSPACE/daily/ssss/pure/android"
+echo "build $WORKSPACE/daily/ssss/obm/android"
+#build "$WORKSPACE/daily/ssss/obm/android" | tee /tmp/ssss-obm.log
 backup
 
-echo "build $WORKSPACE/daily/ssss/base/android $GBC_FEATURE_PROVIDER_PATH/project_config/GSmart_SSSS.cfg"
-build "$WORKSPACE/daily/ssss/base/android" "$GBC_FEATURE_PROVIDER_PATH/project_config/GSmart_SSSS.cfg"
-backup
+echo "repo-sync $WORKSPACE/korg-mirror"
+repo-sync "$WORKSPACE/korg-mirror" || echo "mirror: repo-sync fail"
 
